import Navbar from "@/components/Navbar";
import Head from "next/head";
import Image from 'next/image'
import { useSession, signOut, signIn } from 'next-auth/react'
import { useSearchParams } from 'next/navigation';
import { Icon } from '@iconify/react';

export default function Login() {

    const searchParams = useSearchParams();

    // Get redirect address from Search Params
    const search = searchParams.get('redirect_to') ?? '/'

    return (
        <>
            <Head>
                <title>Studio Gek | Login</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header>

            </header>

            <main>
                <div className='h-screen bg-base-300'>
                    <div className="flex flex-col justify-center items-center">
                        <div className="card w-96 flex flex-col justify-center items-center bg-base-100 mt-20 shadow-xl">
                            <Image width="256" height="256" src="/static/logo_white.png" />
                            <div className="card-title text-">Thanks for joining us at Studio Gek!</div>
                            <div className="card-title font-thin text-md">Please login to continue</div>
                            <div className="divider"></div>
                            <div className="card-body">

                                <button className="btn mt-2 bg-[#F96854] text-white border-0"
                                    onClick={() => signIn('patreon', {
                                        callbackUrl: `${window.location.origin}/${search}`
                                    })}>
                                    <Icon className="mr-2" icon="mdi:patreon" />Continue with Patreon</button>

                                <span className="text-xs p-3 text-center">By continuing, you agree to <a className="link font-bold">Studio Gek's <br />Privacy Policy</a></span>
                            </div>



                        </div>
                    </div>
                </div >

            </main >

            <footer>

            </footer>

        </>
    )
}