import Navbar from "@/components/Navbar";
import Head from "next/head";
import { Image } from "@nextui-org/react";
import { useSession, signOut, signIn } from 'next-auth/react'
import { useSearchParams } from 'next/navigation';
import { Icon } from '@iconify/react';
import { Button, Card, Container, Grid, Text } from "@nextui-org/react";

export default function Login() {

    const searchParams = useSearchParams();

    // Get redirect address from Search Params
    const redirectURL = searchParams.get('redirect_to') ?? '/'

    return (
        <>
            <Head>
                <title>Studio Gek | Login</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header>

            </header>

            <main>

                <Container css={{ mt: "$2xl" }} justify="center" alignItems="center" alignContent="center" display="flex" >

                    <Card variant="bordered" css={{ mw: "400px", d: "flex", justifyContent: "center", alignItems: "center" }}>
                        <Card.Header css={{}}>
                            <Image width={200} height={200} src="/static/logo_white.png" />
                        </Card.Header>

                        <Card.Header css={{ d: "flex", justifyContent: "center", flexDirection: "column" }}>
                            <Text h4>Welcome to Studio Gek</Text>
                            <Text weight={"thin"} h5>To get started, login to your Patreon account</Text>
                        </Card.Header>

                        <Card.Body>

                            <Button
                                onClick={() => signIn('patreon', {
                                    callbackUrl: `${redirectURL}`,

                                })}
                                auto icon={<Icon icon={"mdi:patreon"} />} >
                                Continue with Patreon
                            </Button>

                        </Card.Body>

                        <Card.Footer css={{ d: "flex", justifyContent: "center" }}>
                            <Text>By continuing, you agree to our <a className="link font-bold"> Privacy Policy</a></Text>
                        </Card.Footer>
                    </Card>


                </Container>



            </main >

            <footer>

            </footer>

        </>
    )
}