import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'



export default function Home() {

  const [data, setData] = useState();

  const handleClick = async () => {
    const results = await fetch('/api/patreon/tier')
      .then(res => res.json());

    setData(results.data);

  }

  return (
    <>
      <Head>
        <title>Patreon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <button onClick={() => handleClick()} class="btn">Get Data</button>

      {data}

    </>
  )
}
