import Head from 'next/head'
import React, { useEffect, useState } from 'react'
import { useSession, signOut, signIn } from 'next-auth/react'
import Navbar from '@/components/Navbar';


export default function Home() {

  const [tier, setTier] = useState();
  const { data: session, status } = useSession();
  const tierList = require("../config/tiers")


  useEffect(() => {
    if (!session) {
      // do stuff
      return;
    }

    // Fetch the tierID from the users Patreon profile
    const getUserTier = async () => {
      const results = await fetch('/api/patreon/user/tier')
        .then((res) => {
          return res.json();
        })


      // Filter out the tier from tierList.json
      const tierObject = tierList.find((tier) => tier.id === results.data);

      // Update state
      setTier(tierObject)

    };

    getUserTier()



  })

  return (
    <>
      <Head>
        <title>Patreon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>

        <Navbar tier={tier} />

        <div className='bg-base-300'>
          <section className="text-center">
            Content
          </section>
        </div>

      </main>
    </>
  )
}
