import Head from 'next/head'
import React, { useEffect, useState } from 'react'
import { useSession, signOut, signIn } from 'next-auth/react'
import Navbar from '@/components/Navbar';
import fetchCampaignPost from '@/utils/fetch_campaign_post';
import { useRouter } from 'next/router'
import { Icon } from '@iconify/react';


export default function Post() {

    const [post, setPost] = useState();

    // Get search params
    const router = useRouter();
    const { pid } = router.query;


    // Get post from search params
    const getPost = async (id) => {
        const results = await fetchCampaignPost(id);
        setPost(results.data);

    }

    useEffect(() => {

        // If search param isn't ready don't try.
        if (!pid) {
            return
        }

        // Call our asyncronous function
        getPost(pid)

        return () => {
            // this now gets called when the component unmounts
        }


    }, [pid])

    return (
        <>
            <Head>
                <title>Studio Gek | Post</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header>
                <Navbar />
            </header>

            <main>
                <div className='h-screen bg-base-200'>
                    <section className="flex flex-col items-center align-middle">


                        <h1>{post?.attributes.title}</h1>
                        <button className="btn mt-2 bg-[#F96854] text-white border-0"
                            onClick={{}}>
                            <Icon className="mr-2" icon="mdi:patreon" />View post on Patreon</button>

                    </section>
                </div >

            </main >

            <footer>

            </footer>

        </>
    )
}