import Head from 'next/head'
import React, { useEffect, useState } from 'react'
import { useSession, signOut, signIn } from 'next-auth/react'
import Navbar from '@/components/Utility/Navbar';
import fetchCampaignPost from '@/utils/fetch_campaign_post';
import { useRouter } from 'next/router'
import { Icon } from '@iconify/react';
import { Container, Text, Button, Spacer } from '@nextui-org/react';
import parse from "html-react-parser"
import Link from 'next/link';


export default function Post() {

    const [post, setPost] = useState();
    const [streamableId, setStreamableId] = useState();
    const [postContent, setPostContent] = useState("")

    // Get search params
    const router = useRouter();
    const { pid } = router.query;



    // Get the seven digits at the end of the post url
    function getPostID(str) {
        const regex = /\d{8}$/; // match the last 7 digits
        const match = str.match(regex);
        console.log(match)
        return match ? match[0] : null;
    }


    // Get post from search params
    const getPost = async (id) => {

        const results = await fetchCampaignPost(id);
        setPost(results.data);

        const urlId = getStreamableLink(results.data?.attributes.content);
        setStreamableId(urlId)
    }


    // Get streamable link from the post
    const getStreamableLink = (text) => {

        const pattern = /https?:\/\/(?:www\.)?streamable\.com\/(\w{6})/;
        // Use the match method to extract an array of all matches
        const matches = text?.match(pattern);

        // Map the last 6 characters of each match
        if (matches) {
            const match = matches.map(match => match.slice(-6));
            return match[0]
        }

        return null;

    }


    useEffect(() => {

        // If search param isn't ready don't try.
        if (!pid) {
            return
        }

        // Call our asyncronous function
        const id = getPostID(pid);
        getPost(id)

        return () => {
            // this now gets called when the component unmounts
        }


    }, [pid])


    return (
        <>
            <Head>
                <title>Studio Gek | Post</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header>
                <Navbar />
            </header>

            <main>

                <Container gap={0} lg>

                    {!streamableId &&
                        <div>
                            <Text h1>{post?.attributes.title}</Text>
                            <div dangerouslySetInnerHTML={{ __html: post?.attributes.content }} />

                            <a target="_blank" href={`https://patreon.com${post?.attributes.url}`}>
                                <Button auto icon={<Icon icon={"mdi:patreon"} />} color="gradient">
                                    View post on Patreon
                                </Button>
                            </a>
                        </div>
                    }

                    {streamableId &&

                        <Container css={{ mt: "$10", mb: "$10" }} alignContent='center' justify='center' display='flex' direction='column'>

                            <Text css={{ ta: "center" }} h1>{post?.attributes.title}</Text>

                            <iframe

                                style={{
                                    border: "2px solid "
                                }}
                                src={`https://streamable.com/o/${streamableId}`}
                                width="1600"
                                height="900" allowFullScreen>
                                Browser not compatible
                            </iframe>
                        </Container>
                    }

                </Container>


            </main >

            <footer>

            </footer>

        </>
    )
}