import Head from 'next/head'
import React, { useEffect, useState } from 'react'
import { useSession, signOut, signIn } from 'next-auth/react'
import Navbar from '@/components/Navbar';
import PostCard from '@/components/PostCard';
import fetchUserTier from '@/utils/fetch_user_tier';
import fetchCampaignPosts from '@/utils/fetch_campaign_posts'


export default function Post() {

    // const { data: session, status } = useSession()

    // const [userTier, setUserTier] = useState();
    // const [postData, setPostData] = useState([]);

    // // Get all of the posts from the campaign
    // const getPosts = async () => {
    //     const results = await fetchCampaignPosts();
    //     setPostData(results.data);
    // }

    // // Get the current tier of the user
    // const getTier = async () => {
    //     const results = await fetchUserTier();
    //     setUserTier(results);
    // }
    // useEffect(() => {

    //     // Call our asyncronous functions
    //     getTier()
    //     getPosts()


    //     return () => {
    //         // this now gets called when the component unmounts
    //     }


    // }, [])
    // // Loop over all post data
    // const PostItems = () => {
    //     return (
    //         postData.map((data) => {
    //             return <PostCard props={data} />
    //         })
    //     )
    // }

    // if (status === "loading") {
    //     return <p>Loading...</p>
    // }

    // if (status === "unauthenticated") {
    //     return <p>Please login to view this page</p>
    // }



    return (
        <>
            <Head>
                <title>Studio Gek | Home</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header>
                <Navbar />
            </header>

            <main>
                <div className='h-screen bg-base-200'>
                    <section className="flex flex-col items-center align-middle">

                        <h1 className="text-2xl">Attack on Titan: Episode 1</h1>
                        <div>
                            <iframe src="https://streamable.com/e/879zkt" width="1920" height="1080" frameborder="0" allowfullscreen></iframe>
                        </div>

                    </section>
                </div >

            </main >

            <footer>

            </footer>

        </>
    )
}