import Head from 'next/head';
import { Text, Container } from '@nextui-org/react';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import LoadingSpinner from '@/components/Utility/LoadingSpinner';
import Navbar from '@/components/Layouts/Navbar/index.js';

export default function Reaction() {

    const [post, setPost] = useState();
    const [isLoading, setLoading] = useState(true);

    const router = useRouter();
    const { id } = router.query;

    const getPost = async (id) => {
        const result = await fetch(`/api/posts/post?id=${id}`)
            .then((res) => res.json())
            .catch((err) => alert(err));

        console.log(result.post[0])
        setPost(result.post[0])
        setLoading(false)

    }

    useEffect(() => {

        if (!id) {
            return
        }

        getPost(id)

    }, [id])


    if (isLoading) {
        return (
            <Container css={{ d: "flex", justifyContent: "center", alignItems: "center" }}>
                <LoadingSpinner css={{}} />
            </Container>
        )
    }


    return (
        <>
            <Head>
                <title>Studio Gek | Post</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header>
                <Navbar />
            </header>

            <main>

                <Container gap={0} lg>

                    <Container css={{ mt: "$10", mb: "$10" }} alignContent='center' justify='center' display='flex' direction='column'>

                        <Text css={{ ta: "center" }} h1>{post?.title}</Text>
                        <Container css={{ width: "100%", height: "0px", position: "relative", pb: "56.250%" }}>
                            <iframe src={`https://streamable.com/e/${post?.streamableId}`} frameborder="0" width="100%" height="100%" allowfullscreen style={{ width: "100%", height: "100%", position: "absolute", left: "0", top: "0", overflow: "hidden" }}>
                            </iframe>
                        </Container>
                    </Container>


                </Container>


            </main >

            <footer>

            </footer>

        </>
    )
}
