import Head from 'next/head';
import { Text, Container, Button, Link } from '@nextui-org/react';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import LoadingSpinner from '@/components/Utility/LoadingSpinner';
import Navbar from '@/components/Layouts/Navbar/index.js';
import timeAgo from '@/utils/timeAgo';
import { Icon } from '@iconify/react';
import { signIn, useSession } from 'next-auth/react';

export default function Reaction() {

    const [post, setPost] = useState();
    const [requiredTier, setRequiredTier] = useState();

    const [hasAccess, setAccess] = useState();
    const [isLoading, setLoading] = useState(true);
    const [redirectUrl, setRedirectURL] = useState();

    const { data: session, status } = useSession()

    const router = useRouter();

    const { id } = router.query;

    // Get the post by query parameters
    const getPost = async (id) => {


        const result = await fetch(`/api/posts/post?id=${id}`)
            .then((res) => res.json())
            .catch((err) => console.log(err));

        if (result.status === 401) {
            setAccess(false);
            setRequiredTier(result.data)
        } else if (result.status === 200) {
            setAccess(true)
            setPost(result.data[0])
        }

        setLoading(false)

    }

    useEffect(() => {

        if (!id) {
            return
        }

        getPost(id)

        setRedirectURL()


    }, [id])

    // Convert tag into nice looking text
    function hyphenToTitleCase(str) {
        return str
            .split("-")
            .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
            .join(" ");
    }

    return (
        <>
            <Head>
                <title>Studio Gek | Post</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header>
                <Navbar />
            </header>

            <main>

                <Container gap={0} lg>


                    {hasAccess &&

                        < Container css={{ mt: "$10", mb: "$10" }} alignContent='center' justify='center' display='flex' direction='column'>
                            <Text h1 b> {post?.title}</Text>
                            <Text h4>Posted {timeAgo(post?.timestamp)}</Text>
                            <Text as={Link} isExternal color="primary" href={`/reaction/tags/${post?.tag}`}>Watch more {hyphenToTitleCase(post?.tag)}</Text>
                            <Container css={{ mt: "$10", width: "100%", height: "0px", position: "relative", pb: "56.250%" }}>
                                <iframe src={`https://streamable.com/e/${post?.streamableId}`} frameborder="0" width="100%" height="100%" allowFullScreen style={{ width: "100%", height: "100%", position: "absolute", left: "0", top: "0", overflow: "hidden" }}>
                                </iframe>
                            </Container>
                        </Container>
                    }

                    {!hasAccess && status === "authenticated" && !isLoading &&
                        <>
                            <Text>
                                Hey it appears you don't have access to this content, sorry about that.
                            </Text>
                            <Button>Join Patreon</Button>
                        </>

                    }

                    {isLoading &&

                        <Container css={{ d: "flex", justifyContent: "center", alignItems: "center" }}>
                            <LoadingSpinner css={{}} />
                        </Container>

                    }

                    {status === "unauthenticated" &&
                        <>
                            <Text>
                                Please login to view the requested content
                            </Text>

                        </>
                    }

                </Container>


            </main >

            <footer>

            </footer>

        </>
    )
}
