import Head from 'next/head';
import { Text, Container, Button, Link, Badge, Modal } from '@nextui-org/react';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import LoadingSpinner from '@/components/Utility/LoadingSpinner';
import Navbar from '@/components/Layouts/Navbar/index.js';
import timeAgo from '@/utils/timeAgo';
import { useSession } from 'next-auth/react';
import hyphenToTitleCase from '@/utils/hyphenToTitleCase';
import { Icon } from '@iconify/react';

export default function Reaction() {

    const [post, setPost] = useState();
    const [requiredTier, setRequiredTier] = useState();

    const [hasAccess, setAccess] = useState();
    const [isLoading, setLoading] = useState(true);
    const [redirectUrl, setRedirectURL] = useState();

    const { data: session, status } = useSession()

    const router = useRouter();

    const { id } = router.query;

    // Get the post by query parameters
    const getPost = async (id) => {


        const result = await fetch(`/api/posts/post?id=${id}`)
            .then((res) => res.json())
            .catch((err) => console.log(err));


        // This is some hacky shit I should probably rewrite but oh well
        if (result.status === 401) {
            setAccess(false);
            setRequiredTier(result.data)
        } else if (result.status === 200) {
            setAccess(true)
            setPost(result.data[0])
        }

        setLoading(false)

    }

    useEffect(() => {

        // If we haven't loaded yet don't try to use query params
        if (!id) {
            return
        }

        getPost(id)

    }, [id])



    return (
        <>
            <Head>
                <title>Studio Gek | Post</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header>
                <Navbar />
            </header>

            <main>


                <Container gap={0} lg  >


                    {hasAccess &&

                        <Container Container css={{ mt: "$10", mb: "$10" }} alignContent='center' justify='center' display='flex' direction='column'>
                            <Text size={20}> {post?.title} {post?.seasonNumber}x{post?.episodeNumber}</Text>
                            <Text size={18} color="$accents6">Posted {timeAgo(post?.timestamp)}</Text>
                            <Text as={Link} color="primary" href={`/reaction/tags/${post?.tag.safeTitle}`}>Watch more {post?.tag.title}</Text>
                            <Container css={{ mt: "$10", width: "100%", height: "0px", position: "relative", pb: "56.250%" }}>
                                <iframe src={`https://streamable.com/e/${post?.streamableId}`} frameborder="0" width="100%" height="100%" allowFullScreen style={{ width: "100%", height: "100%", position: "absolute", left: "0", top: "0", overflow: "hidden" }}>
                                </iframe>
                            </Container>

                        </Container>
                    }

                    {/*If we don't have access and we're logged in*/}
                    {!hasAccess && status === "authenticated" && !isLoading &&
                        <Container gap={0} display='flex' direction='column' alignItems='center' css={{ p: 20 }} >
                            <Modal
                                preventClose={true}
                                blur
                                aria-labelledby="modal-title"
                                open={true}

                            >
                                <Modal.Header>
                                    <Text id="modal-title" size={20}>
                                        403 Forbidden
                                    </Text>
                                </Modal.Header>
                                <Modal.Body>
                                    <Text css={{ ta: 'center   ' }}>You must be <Text b>{requiredTier}</Text> to view this content</Text>
                                </Modal.Body>
                                <Modal.Footer css={{ d: 'flex', justifyContent: "center" }}>
                                    <Button onPress={() => router.push('/')} flat icon={<Icon width={20} icon="mdi:home" />} auto color="primary" >
                                        Back Home
                                    </Button>
                                    <Button flat auto color="warning" onPress={(() => router.push('https://www.patreon.com/studiogek'))} icon={<Icon width={20} icon="mdi:patreon" />}>
                                        Join Patreon
                                    </Button>
                                </Modal.Footer>
                            </Modal>
                        </Container>

                    }

                    {/* Loading state*/}
                    {isLoading &&

                        <Container css={{ d: "flex", justifyContent: "center", alignItems: "center" }}>
                            <LoadingSpinner css={{}} />
                        </Container>

                    }


                    {/*If we're unauthenticated and the post isn't a public post force a login */}
                    {status === "unauthenticated" && post?.tier.id !== "0000000" &&
                        <>
                            <Text>
                                Please login to view the requested content
                            </Text>
                        </>
                    }

                </Container>


            </main >

            <footer>

            </footer>

        </>
    )
}
